language: c
sudo: false

cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

git:
  depth: false
  quiet: true

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

install:
  # Note that every library should be installed in a seperate command
  - arduino --install-library "Arduino Sensor"
  - arduino --install-library "DHT sensor library"

script:
  - build_platform esp8266
